all: server client server1 client1
server: server.c
	gcc	-o	server	server.c

server1: server1.c
	gcc	-o	server1	server1.c

client: client.c	
	gcc	-o	client	client.c

client1: client1.c	
	gcc	-o	client1	client1.c
clean:
	rm -f *.o *~